### ISSUE TITLE
Cannot change tabViewBackgroundDefaultColor of each tab.

### ISSUE THREAD

**Issue by chhaysotheara** [nrlnishan/ViewPager-Swift#11]
Thank you for your awesome library.
I have 5 tabs and I want the entire tabView to change to the color of each tab.
Example: tab 1 -> blue, tab 2 -> green
-When clicked on tab 1 (both tab 1 and tab 2 change its background to blue).
-When clicked on tab 2 (both tab 1 and tab 2 change its background to green).
Can you help me out please ?

**Comment by nrlnishan** [comment]
Currently there is no easy way to do that. You would have to modify the internal code.

You can do it in following way : [ PS: I havn't tested it ]

1. remove the fileprivate access modifier for `tabContainer` in ViewPagerController.swift [ line 36 ]
2. Delegate method will be called each time you change the page. so when you press on each tab, page will change as a result, delegate will be called. 
3. Now directly change the` background colo`r of `tabContainer` from within that delegate method.
i.e from `didMoveToViewControllerAtIndex` method.
4. You will have to set `isTabHighlightAvailable` to false for `ViewPagerOptions`

This should change the background color for all tabs to your provided color, when any of the tab is tapped.

**Comment by eastswift** [comment]
I'm sorry. It was my mistake. Your open source is Cool! Have a nice day :)

**Comment by chhaysotheara** [comment]
I have add some code to change color of tabsViewList in pageViewController and ChosenViewController method.

It work. Thank you so much.
