### ISSUE TITLE
how to change tab title from any pages

### ISSUE THREAD

**Issue by sahabe1** [nrlnishan/ViewPager-Swift#12]
I want to change the page title based on the api call from any pages. how can i do this

**Comment by nrlnishan** [comment]
Tab title is based on `ViewPagerTab` object which is provided through its datasource method
`func tabsForPages() -> [ViewPagerTab]`. 

The way you can do is, 

1. Get whatever information you want from api calls necessary to change `ViewPagerTab`
2. Update the array of `ViewPagerTab` which you are providing as datasource for above mentioned method.

**Comment by sahabe1** [comment]
is it possible to cahnge the tab title from any pages (childview controller)

**Comment by nrlnishan** [comment]
No, The tab title can be only changed from view controller which is the data source for `ViewPagerController`.

Create a custom protocol which notifies Parent view controller ( which is conforming to viewpager datasource ) from Child View Controller. Notify from child view controller and update the view pager tab array.

**Comment by sahabe1** [comment]
thanks, nrlnishan

**Comment by sahabe1** [comment]
Hi nrlnishan, I have created custom protocol but i am not able to update tab title can u please help me how can i update here is my code

extension CartVC : UpdateTabTitleDelegate{
  func didupdatePageTitle() {
    tabs = [
      ViewPagerTab(title: "10\nBuy", image: nil),
      ViewPagerTab(title: String(format: "%@\nWant", "15"), image: nil),
      ViewPagerTab(title: "10\nHistory", image: nil),
    ]
self.tabsForPages()
  }
}

it is not working please help

**Comment by nrlnishan** [comment]
Hi @sahabe1 ,

Since the tab is setup initially, it is only obtained once from datasource. So even if you changed the ViewPagerTab array in datasource, i found that it doesnot get updated. Sorry, This is a silly design mistake in my part. 

I will fix this and try to provide the simple way of updating tabs, i.e indicating that the tabs/content should be refreshed asap along with cocoapod support.

**Comment by nrlnishan** [comment]
@sahabe1 , The above mentioned issue has been fixed and the ability to change the tab has been added. Please checkout the **Additional** section in Readme

Thanks
