### ISSUE TITLE
how to disable particular tab

### ISSUE THREAD

**Issue by sahabe1** [nrlnishan/ViewPager-Swift#13]
hi , Can i disable particular tab

**Comment by nrlnishan** [comment]
No, you can't disable particular tab. How about removing that tab altogether?

Just provice the updated `ViewPagerTab` list in `tabsForPages` method in datasource.

**Comment by nrlnishan** [comment]
Heyy @sahabe1 , Ability to update the tabs have been added. Please checkout **Additional** section in Readme.

Thanks
