### ISSUE TITLE
show reverse

### ISSUE THREAD

**Issue by vre142** [nrlnishan/ViewPager-Swift#14]
Hi 
how can i show items of tabview from right to left ??
default is left to right.
Another question is I want to show default position for example number 5 how can i do this?

Thanks

**Comment by nrlnishan** [comment]
Hi @vre142 , There is no way to show items of tabview from right to left. 

But if you want implement `optional func startViewPagerAtIndex()->Int` method in datasource. Index starts from 0 to (number of view controllers - 1). This displays the view controller required.

Hope it helps
