### ISSUE TITLE
What is the API call to programmatically move to a specific tab?

### ISSUE THREAD

**Issue by robcecil** [nrlnishan/ViewPager-Swift#15]

**Comment by nrlnishan** [comment]
Hi @robcecil , Currently you can only move to specific tab only at the beginning. If thats what you want, please implement the `startViewPagerAtIndex` method in datasource. That corresponding view controller is shown when the "ViewPager" is loaded at the beginning.

If you want to change view controller programatically at any time, please change the `fileprivate` access modifier to `public` in `displayViewController` method from file `ViewPagerController.swift` , line 310. This file is present in `Core` directory.

**Comment by nrlnishan** [comment]
I will include this in next update along with cocoapods support. 
Thanks

**Comment by nrlnishan** [comment]
Hey @robcecil , Feature to move to specific tab has been added. Please checkout **Additional** section in Readme.

Thanks.
