### ISSUE TITLE
How do I indicate my datasource has changed and the tabs/content should be reloaded/refreshed?

### ISSUE THREAD

**Issue by robcecil** [nrlnishan/ViewPager-Swift#16]

**Comment by nrlnishan** [comment]
@robcecil 

Sorry, Currently there is no way. I will try to incorporate those changes asap and update it.

**Comment by robcecil** [comment]
Could the technique be:

- set datasource to nil
- set datasource back

? Not sure if a brute force would have bad side effects though.

**Comment by nrlnishan** [comment]
Hey @robcecil,
ViewController for each page are dynamically obtained, But the tabs are setup during first initialization only. 
Thus changing ViewController for each page works easily by just changing the values provided through datasource whereas for the tabs, it doesnot work. I am working on this issue and will try to update with the fixed verison asap.

**Comment by nrlnishan** [comment]
Hi @robcecil ,

Ability to reload the tabs has been added. Please checkout the **Additional** section in Readme.

Thanks
