### ISSUE TITLE
getting wrong tab index

### ISSUE THREAD

**Issue by sahabe1** [nrlnishan/ViewPager-Swift#18]
Hi, 
viewpager getting wrong index when swiping tabs

when swiping page 0 to 1 then page 2 also called and when swiping from page 2 to 1 then page 0 also called. In my case  i have 3 tabs

**Comment by nrlnishan** [comment]
Hey @sahabe1 , Did you download the `ViewPagerController` file recently? Sorry, i found that i have pushed the wrong file. Now i have reverted it to the previous commit. Can you download the previous file again?

Sorry for the hassle, cocoapod support will be added soon
