### ISSUE TITLE
ViewDidLoad Calling every time when page changed

### ISSUE THREAD

**Issue by sahabe1** [nrlnishan/ViewPager-Swift#19]
Hi, When page is changing viewdidload calling every time . is it possible to call viewdidload once when tab created

**Comment by nrlnishan** [comment]
Current, Before & After UIViewController are loaded whenever ViewPager is setup. Suppose you have 3 pages A,B and C and you started in page 'A'. Then A gets loaded and its 'viewDidLoad' will get called. Now move to page 'B'. This time 'C' also gets loaded. Now 'viewDidLoad' of both B and C gets called.

Now move back to 'A'. This time A's `viewDidLoad` doesnot get called.

Look into implementation of [UIPageViewController](https://developer.apple.com/reference/uikit/uipageviewcontroller) for more details.

**Comment by sahabe1** [comment]
thanks nrlnishan,

is it possible to disable horizontal bouncing

**Comment by nrlnishan** [comment]
@sahabe1 
Can you please elaborate ? What do you mean by horizontal bouncing ?

**Comment by sahabe1** [comment]
horizontal page bouncing please see attachment

![simulator screen shot may 13 2017 4 19 20 pm](https://cloud.githubusercontent.com/assets/1065015/26024839/318cf7a4-37f8-11e7-94a4-a486700b76f8.png)
![simulator screen shot may 13 2017 4 19 27 pm](https://cloud.githubusercontent.com/assets/1065015/26024838/318c03bc-37f8-11e7-9f2d-421df6b2dae0.png)

**Comment by nrlnishan** [comment]
Its the default behaviour of `UIPageViewController`. I think you can change it but please look up in the documentation provided by apple.
