### ISSUE TITLE
how to change first page?

### ISSUE THREAD

**Issue by aboutyu** [nrlnishan/ViewPager-Swift#20]
Hi~
I want to use this source on my App, but I have unresolved issue.

I want to show the ViewController of third position when enter upon first.
How to make it?

**Comment by nrlnishan** [comment]
Hi @aboutyu , There is an optional datasource method `startViewPagerAtIndex`. Return the index of the page which you want to show at first. i.e If third page, index is 2 as index always starts from 0.
