### ISSUE TITLE
Scroll issue

### ISSUE THREAD

**Issue by yashinls** [nrlnishan/ViewPager-Swift#21]
Hi @nrlnishan, I have an issue with the library.

I have 4 tabs. After customizing the ViewPager, I made the ViewPager select the 4th tab with:  viewPager.displayViewController(atIndex: 3). Now the 4th tab is selected. But when I scroll left it goes to the 1st tab instead of 3rd. Could you please check.

**Comment by nrlnishan** [comment]
Hey @yashinls , Issue #6 has been fixed and code is available in master branch. Sorry for the hassle, i will provide with cocoapod support soon.

Regarding this issue #21, I cannot recreate this issue. Are you sure you are not doing anything extra which is causing the problem? Can you provide me the exact step to recreate this issue?

Thanks

**Comment by yashinls** [comment]
Hi @nrlnishan, I ain't doing anything extra. Please see the attached zip file. Try swiping, once the app has loaded. If we swipe to left it goes to 1st tab and if I swipe to right it goes to the last tab.

Btw, I'm testing it in on iOS 8.1. Does it support iOS 8?

[test.zip](https://github.com/nrlnishan/ViewPager-Swift/files/1069038/test.zip)

**Comment by nrlnishan** [comment]
Hey @yashinls , 
Above mentioned issue has been fixed.

**Comment by yashinls** [comment]
Thanks @nrlnishan
