### ISSUE TITLE
I want Viewpager's CurrentViewController

### ISSUE THREAD

**Issue by eastswift** [nrlnishan/ViewPager-Swift#22]
I want to reload the table view of the current view controller of the viewpager by pressing the R button in navigationviewcontroller. I do not know what to do. Can I get the ViewPager current ViewController from the navigationviewcontroller?

**Comment by nrlnishan** [comment]
When you press on the R button in NavigationController, create & send a notification. And inside the viewcontroller that you want to reload, observe for that notification & reload the table view.

Another way is keep track of the index of the current view controller through delegate method, `didMoveToViewController(_:)` method. Then whe you press that button, get the current index, and call `displayViewController(thatCurrentIndex)` method on viewpager.

**Comment by eastswift** [comment]
Must be in real time. For example, how can I change the tableviewcontroller vc0 in the viewpager to Editmode when I press the EDIT button on the table view in the navigation bar? Immediately.
