### ISSUE TITLE
How to update the content of pages after changing language

### ISSUE THREAD

**Issue by sukhpreet011** [nrlnishan/ViewPager-Swift#23]
I am loading viewPager with dynamic contents and custom font. When changing language of the app, how to update the contents of all the pages i.e. reload viewPager.

**Comment by nrlnishan** [comment]
Hey @sukhpreet011 ,

I am providing the reference to the link for reloading the contents within the page.
https://github.com/nrlnishan/ViewPager-Swift/issues/22

Also if you want to update tabs, please refer to the **Additional** section of the **README**. Thanks
