### ISSUE TITLE
Scrolling problem

### ISSUE THREAD

**Issue by vre142** [nrlnishan/ViewPager-Swift#24]
Hi I hame problem when I'm in first index and when I click on fifth index scroll to fifth page but if half of fifth page title is hidden title also hidden and rearrange it. how can i fix it?
Thanks,
Vafa

**Comment by nrlnishan** [comment]
Sorry, i didnot understand what you meant ? can you please elaborate ?

**Comment by vre142** [comment]
Please see this video:
https://streamable.com/6a69v
when I click on last left item I can see in view move to it but we have another item near it and user doesn't know we have another item.

**Comment by nrlnishan** [comment]
Hi @vre142 ,

I see that you have asked this question previously too. I am referencing that same issue link over here. Please check out 2nd comment & tell me if you still have problem. 

Issue #3
