### ISSUE TITLE
The space at the bottom appears.

### ISSUE THREAD

**Issue by eastswift** [nrlnishan/ViewPager-Swift#25]
The space at the bottom appears. 

I used a tab bar.

There is a small margin between the viewpager's viewcontroller and the tabbar. At the bottom

I want to fit this.

**Comment by nrlnishan** [comment]
@eastswift What small margin are you talking about? Can you provide screenshots ?

**Comment by eastswift** [comment]
I can provide a screenshot, but I do not know your email address. I've already captured it.

**Comment by nrlnishan** [comment]
You can upload screenshot at any image uploading site such as [Imgur](http://imgur.com/) and provide the link here

**Comment by eastswift** [comment]
http://imgur.com/iiyaytx

The scroll bar is at the maxium bottom.

**Comment by eastswift** [comment]
I think this is not a bug. It seems like I'm using the tab bar.

**Comment by nrlnishan** [comment]
@eastswift , Thanks for mentioning that. Since its not a bug, I am closing this issue now
