### ISSUE TITLE
Incorrect black space bar on hotspot active or phone call.

### ISSUE THREAD

**Issue by chhaysotheara** [nrlnishan/ViewPager-Swift#26]
Step to reproduce the bug
1. App hasn't been open.
2. During phone call / Hotspot active
3. Open the app it show like this http://imgur.com/a/JJacM , http://imgur.com/a/LnmTd

if the app is currently open or has been open (background and back to active) + step 2 it's okay.

**Comment by chhaysotheara** [comment]
I have modify the ViewPagerController on setupTabContainerView function and add an if condition
if self.view.frame.origin.y > 0 {
            self.view.frame.origin.y = 0
        }
and it work fine now. but I hope you can fix it for future update.

**Comment by nrlnishan** [comment]
Hey @chhaysotheara ,
Thanks. I will leave this issue open for anybody neeeding this hotfix for now and will fix this issue in next update. 
Thanks again :)
