### ISSUE TITLE
Disable horizontal scrolling in content view

### ISSUE THREAD

**Issue by titopalito** [nrlnishan/ViewPager-Swift#27]
I want to chance views only when tapping the tabs and disable changing page by swipe the content view
I'll appreciate any comment.
Thank you very much.

**Comment by nrlnishan** [comment]
Heyyy @titopalito ,

Currently there is not any method for disabling the swipe gesture. But you can change the internal implementation of ViewPager to disable the changing of page while swiping. 

Please comment the line **271** in `ViewPagerController.swift` file. 

i.e comment this line 
`// ViewPagerController.swift`

This should disable the default swiping. 

Thanks

**Comment by titopalito** [comment]
Wow, very fast answering.
It worked very well, thanks a lot

**Comment by nrlnishan** [comment]
@titopalito 
Glad it helped. I am closing this issue now
