### ISSUE TITLE
Adding Different View Controller

### ISSUE THREAD

**Issue by Gouthamansriniv** [nrlnishan/ViewPager-Swift#28]
How Can i Add Different view controller for different page . thanks in advance
 @nrlnishan

**Comment by nrlnishan** [comment]
Hey @Gouthamansriniv , Just implement the `datasource` method `func viewControllerAtPosition(position:Int) -> UIViewController`. Return the ViewController that you want at respective page

**Comment by Gouthamansriniv** [comment]
var viewControllersArray:[UIViewController] = {
        
        let sb = UIStoryboard(name: "Main", bundle: nil)
        
        let vc1 = sb.instantiateViewController(withIdentifier: "infoListVC")
        let vc2 = sb.instantiateViewController(withIdentifier: "usersVC")
        let vc3 = sb.instantiateViewController(withIdentifier: "staticVC")

        
        return [vc1, vc2, vc3]
        
    }()



How can i able to call in this function
func viewControllerAtPosition(position:Int) -> UIViewController {
        
        
        let vc1 = self.storyboard?.instantiateViewController(withIdentifier: "infoListVC") as! ChatListVC
        return vc1
    }

Thanks.

**Comment by nrlnishan** [comment]
Here is an example of how to use Viewpager library. [Example](https://github.com/nrlnishan/ViewPager-Swift/blob/master/ViewPager-Swift/MainViewController.swift)

**Comment by Gouthamansriniv** [comment]
Thanks for your help @nrlnishan
