### ISSUE TITLE
how can I add more than one view controllers within a tab

### ISSUE THREAD

**Issue by prakhila** [nrlnishan/ViewPager-Swift#29]

**Comment by prakhila** [comment]
Adding more than one view controllers within a tab
Iam a beginner in swift programming..hope u will help me ,thanks in advance
     var tabs =
        [
        ViewPagerTab(title: "Products", image: UIImage(named: "icons8-Gift-50 copy.png")),
        ViewPagerTab(title: "Deals", image: UIImage(named: "icons8-Handshake-50.png")),
        ViewPagerTab(title: "Groups", image: UIImage(named: "icons8-People Filled-50 copy.png")),
        ViewPagerTab(title: "Chat", image: UIImage(named: "icons8-Message Filled-50.png")),
        ViewPagerTab(title: "Folder", image: UIImage(named: "icons8-User Folder-50 copy.png")),
       
                 ]
    
On clicking on the titles of the tab I want different view controllers to display

**Comment by nrlnishan** [comment]
Hey @prakhila ,

It seems that you are beginner to swift. Please learn about datasource & delegate.

Viewpager utilizes this datasource pattern. You need to conform to ViewPagerDataSource. and implements the methods. 

Checkout `MainViewController.swift` file [Link](https://github.com/nrlnishan/ViewPager-Swift/blob/master/ViewPager-Swift/MainViewController.swift) On line `62,63` i set datasource of view pager and on line `74 - 9`4 i implement the DataSource method. This datasource method provides the ViewController which is to be displayed when the tabs are tapped.

**Comment by prakhila** [comment]
yaa got it thank you..

**Comment by nrlnishan** [comment]
@prakhila , Happy to help. Closing this
