### ISSUE TITLE
show two and half of items in view pager

### ISSUE THREAD

**Issue by vre142** [nrlnishan/ViewPager-Swift#3]
Hi,
I want to customize items width in view pager and show 2 or 3 and half of items because I want use knows we have more item in our app. what can I do?
Thanks,
Vafa

**Comment by nrlnishan** [comment]
Hi, 
Do you mean that each tabs width? (shown as Coffee, Donut etc in screenshots ?). If yes, then 

The number of tabs which gets displayed depends upon the width of the device screen. Depending upon the number of tabs and the size of the screen, it may show 2 or 3 tabs and **half of another item**. 

Set `isEachTabEvenlyDistributed = true` (if you want all tabs to be of same width else set false )  and change `tabLabelPaddingLeft` and `tabLabelPaddingRight `values to obtain the desired outcome.

**Comment by vre142** [comment]
Thank you for your response I fix it with your solution. I have another problem how can i change uifont of titles of tabs?
Thanks

**Comment by nrlnishan** [comment]
Currently, it doesn't support changing the font size. But as a workaround you would have to manually add code inside `ViewPagerController.swift` file. 
Add code to change the font size after line `107 ` and after line `130 ` on that `label` variable. 

I will try to incorporate this feature, refactor the codes and fix other issues asap.

**Comment by nrlnishan** [comment]
Hi, 
Support for custom font has been added along with swift3 support. Use `tabViewTextFont` option from ViewPagerOptions class. Please find relevant codes in master branch.
