### ISSUE TITLE
ParentViewController buttons not working

### ISSUE THREAD

**Issue by ibhavin** [nrlnishan/ViewPager-Swift#32]
I have implemented ViewPager in my project successfully and its works well.
Here is my view example:
![screen shot 2017-12-01 at 2 38 51 pm](https://user-images.githubusercontent.com/16459948/33475719-71c2c0a0-d6a5-11e7-945b-611877aa7cac.png)

Tabs working perfectly, but if I click on 'Online images' & 'Offline images' button it did not trigger its action.

Demo Project:
[ViewPager-Swift-master 2.zip](https://github.com/nrlnishan/ViewPager-Swift/files/1521656/ViewPager-Swift-master.2.zip)

**Comment by nrlnishan** [comment]
Can you please elaborate? what do you mean by button not working ?

Have you set the tabs correctly ?  You should conform to `ViewPagerControllerDataSource` protocol , and provide the necessary tabs in `tabsForPages` method.

**Comment by ibhavin** [comment]
@nrlnishan  I have edited issue with demo project. Please check.

**Comment by nrlnishan** [comment]
I found the issue, It seems that the view of the viewpager is overflowing and covering the button.

Here is the workaround:

Create an outlet to that UIButton ( named button over here) and add this line
`self.view.bringSubview(toFront: button)`
after setting up viewpager. 

I will fix this issue asap. 

Thank you for pointing out this issue.
