### ISSUE TITLE
Issue with TabView height on navigation bar hidden

### ISSUE THREAD

**Issue by janeshsutharios** [nrlnishan/ViewPager-Swift#38]
When we hide navigation bar on main view controller tabview height is half on first launch. Kindly look into.

**Comment by janeshsutharios** [comment]
I have created pull request which resolves the issue.

**Comment by Pinturaj** [comment]
When we hide navigation bar on main view controller and I want to add my custom view for header,
But pager takes y from zero.
How to customize height of pager controller.

**Comment by mhNirob** [comment]
I am having the same issue. Can you please tell me how you solved it? @janeshsutharios

**Comment by janeshsutharios** [comment]
@mhNirob combine #39 & #40 pull request. 👍

**Comment by nrlnishan** [comment]
This issue has been fixed in recent update to library. Please refer to the documentation.
