### ISSUE TITLE
View Pager Background changes to Tabs colour

### ISSUE THREAD

**Issue by arshu-dev** [nrlnishan/ViewPager-Swift#4]
Hi,
Thanks for the awesome library. 

I saw a problem that if we change the tabs background colour the whole view pager background colour is also changed to that colour.

Also, if we have only 2 tabs then the selected tab indicator shows for both tabs after sliding for some 3-4 times.

**Comment by nrlnishan** [comment]
Hi,
I have fixed above mentioned issues and pushed new code. Check it out. Sorry for delay.

Thanks.
