### ISSUE TITLE
How to AutoScroll

### ISSUE THREAD

**Issue by ErAshu** [nrlnishan/ViewPager-Swift#49]
How to auto scroll the tab.

Example
i have 10 tabs but on screen 4 tabs showing at a time. What I need, when in tapped last visible tab, it should auto scroll to left so that another tab visible.

similarly when I reach to 2nd tab then it should auto scroll 1st tab to visible.

**Comment by nrlnishan** [comment]
Hi @ErAshu , 

Currently the library has no functionality for showing invisible tab.
