### ISSUE TITLE
Decrease the pageController Hieght 

### ISSUE THREAD

**Issue by DataProgrammer163** [nrlnishan/ViewPager-Swift#5]
Its a Good Control and iam not able to customise i want to decrease the height  of the PageView Controller and I want the titles Tab but i want to show it  Half of the Screen Like Around  y Position should be from 200 i tried but now able to decrease the Frame of the Pagecontroller  can u tell me How to DO it thanks in Advance

**Comment by nrlnishan** [comment]
Hi, 
Currently you can't do it but as a work around please provide y position on line `180` in place of `options.tabViewHeight` in `ViewPagerController.swift` file.

I will try to incorporate all these changes and provide it in next update asap.

**Comment by nrlnishan** [comment]
Hi, 
This feature has been provided in support for swift 3. All relevant code has been updated in master branch. Use `viewPagerPosition` option from ViewPagerOptions class. Provide its y value 200.
