### ISSUE TITLE
How to hide/show Viewpager?

### ISSUE THREAD

**Issue by ib7sandbox** [nrlnishan/ViewPager-Swift#58]
i need to hide this view pager tabs , and then show my other uiview ? how can i achieve this programatically ?

**Comment by nrlnishan** [comment]
Hi @ib7sandbox , 

Can you clarify what you meant by hiding view pager tabs & show other uiviews?

**Comment by ib7sandbox** [comment]
hi @nrlnishan ,

In my viewcontroller , i have one viewpager view and other view on top of it , i need to switch between two views by hiding / showing the views . in viewpager view i can hide content view but i am unable to hide viewpager tabs.  

Can you suggest something so that i can switch between two views by hiding and showing viewpager view ?

**Comment by ib7sandbox** [comment]
hi @nrlnishan ,
i couldn't hide viewpagerTabview but i have fixed my issue, by hiding all subviews.
