### ISSUE TITLE
willMoveToControllerAtIndex is not working

### ISSUE THREAD

**Issue by ninadkambli17** [nrlnishan/ViewPager-Swift#8]
I need a callback on tab selected in view pager. willMoveToControllerAtIndex(index : Int) method is not getting called.

**Comment by nrlnishan** [comment]
Hi @ninadkambli17 . I have fixed the issue and pushed it. Please check it out.

**Comment by ninadkambli17** [comment]
Hi @nrlnishan hats off to response time and resolution time.
