### ISSUE TITLE
How to add another label jsut above the page title

### ISSUE THREAD

**Issue by sahabe1** [nrlnishan/ViewPager-Swift#9]
Hi 
 I want to add label just above to page title can i do this.please see attachment
![unnamed](https://cloud.githubusercontent.com/assets/1065015/23581476/9eaa5f24-013a-11e7-9f6c-7a6dbe1b8062.png)

**Comment by nrlnishan** [comment]
Hey @sahabe1 , Your issue has been fixed and code has been updated in master branch. 

For multiple line in your case ,create tabs as
`ViewPagerTab(title: "9\nBuy", image: nil)`
